#? btop config -- Tokyo Night
color_theme = "tokyo-night"
theme_background = False
truecolor = True
vim_keys = True
rounded_corners = True
update_ms = 1500
proc_sorting = "cpu lazy"
proc_tree = False
show_battery = True
